notebook that was used to generate figures for paper

In [1]:
import scipy
import scipy.sparse, scipy.stats
import numpy
import os
import re
import multiprocessing
import subprocess
import pickle
import matplotlib.pyplot
import time
import statistics
import sklearn
import statsmodels , statsmodels.api
import itertools

In [2]:
def moving_integration (values, window):
    weights = numpy.repeat(1.0, window)
    sma = numpy.convolve(values, weights, 'same')
    return sma
def moving_average (values, window):
    weights = numpy.repeat(1.0, window)/window
    sma = numpy.convolve(values, weights, 'same')
    return sma

In [4]:
with open("../testdata/T_cell_0.10_final_alldata.pickle","rb") as picklefile:
    CSR_mat,frag_index,frag_prop,frag_amount,valid_chroms,chroms_offsets,smoothed_diagonal, refined_peaks ,quick_peaks, peak_p_vals , peaks_q_vals = pickle.load(picklefile)

In [8]:
#distribution of reads frequency
%matplotlib qt

fig = matplotlib.pyplot.figure()
ax = fig.add_subplot(111)

ax.hist(smoothed_diagonal, bins=100, range=(0,100))

(array([289197., 128985., 248440., 227761., 315102., 294979., 340000.,
        310868., 325646., 292770., 289002., 259874., 245865., 221689.,
        207241., 186769., 173913., 157872., 146130., 133952., 124304.,
        114036., 106027.,  98038.,  90597.,  84550.,  78626.,  73346.,
         68627.,  63483.,  60141.,  55603.,  52713.,  48819.,  45529.,
         43135.,  40640.,  37745.,  35206.,  33478.,  31217.,  29538.,
         27914.,  26261.,  24512.,  23126.,  22021.,  21235.,  20093.,
         18764.,  18058.,  17068.,  16272.,  15584.,  14886.,  14251.,
         13443.,  13045.,  12302.,  11921.,  11344.,  10736.,  10293.,
          9915.,   9649.,   9169.,   8779.,   8431.,   8024.,   7859.,
          7640.,   7462.,   7143.,   6913.,   6609.,   6626.,   6131.,
          5861.,   5814.,   5638.,   5571.,   5330.,   5132.,   5007.,
          4915.,   4659.,   4654.,   4499.,   4410.,   4133.,   4176.,
          4047.,   3952.,   3881.,   3757.,   3624.,   3558.,   3535.,
      

In [33]:
# distribution of p values after binomial model
%matplotlib qt

fig = matplotlib.pyplot.figure()
ax = fig.add_subplot(111)


ax.hist(peak_p_vals, bins=20, range=(0,1))

(array([845420., 298147., 278410., 277179., 282318., 281376., 305076.,
        310974., 319878., 312041., 397941., 323357., 420140., 401751.,
        330652., 352053., 339556., 384518., 248440., 418182.]),
 array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
        0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  ]),
 <a list of 20 Patch objects>)

In [ ]:
bedtools annotate -counts -i T_cell_0.001_final_peaks.bed -files T_helper_replicated_peaks.bed | sort -k6,6 -r -g > coverage_data/T_cell_0.001_final_peaks.bed
bedtools annotate -counts -i T_cell_0.01_final_peaks.bed -files T_helper_replicated_peaks.bed | sort -k6,6 -r -g > coverage_data/T_cell_0.01_final_peaks.bed
bedtools annotate -counts -i T_cell_0.10_final_peaks.bed -files T_helper_replicated_peaks.bed | sort -k6,6 -r -g > coverage_data/T_cell_0.10_final_peaks.bed


In [35]:
%matplotlib qt

fig = matplotlib.pyplot.figure()
ax = fig.add_subplot(111)

with open("../testdata/coverage_data/T_cell_0.001_final_peaks.bed") as data:
    graph_data_x=[]
    graph_data_y=[]
    for line in data:
        line_info = line.split()
        graph_data_x.append(int(line_info[2])-int(line_info[1]))
        graph_data_y.append(float(line_info[6]))


ax.plot(numpy.array(graph_data_x).cumsum(),numpy.array(graph_data_y).cumsum())

with open("../testdata/coverage_data/T_cell_0.01_final_peaks.bed") as data:
    graph_data_x=[]
    graph_data_y=[]
    for line in data:
        line_info = line.split()
        graph_data_x.append(int(line_info[2])-int(line_info[1]))
        graph_data_y.append(float(line_info[6]))


ax.plot(numpy.array(graph_data_x).cumsum(),numpy.array(graph_data_y).cumsum())

with open("../testdata/coverage_data/T_cell_0.10_final_peaks.bed") as data:
    graph_data_x=[]
    graph_data_y=[]
    for line in data:
        line_info = line.split()
        graph_data_x.append(int(line_info[2])-int(line_info[1]))
        graph_data_y.append(float(line_info[6]))


ax.plot(numpy.array(graph_data_x).cumsum(),numpy.array(graph_data_y).cumsum())

ax.scatter(125462713,32969)

#0.05
#ax.scatter(41530,32969)

In [23]:
bedtools annotate -counts -i GM12878_0.001_final_peaks.bed -files GM12878_replicated_peaks.bed | sort -k6,6 -r -g > coverage_data/GM12878_0.001_final_peaks.bed
bedtools annotate -counts -i GM12878_0.01_final_peaks.bed -files GM12878_replicated_peaks.bed | sort -k6,6 -r -g > coverage_data/GM12878_0.01_final_peaks.bed
bedtools annotate -counts -i GM12878_0.10_final_peaks.bed -files GM12878_replicated_peaks.bed | sort -k6,6 -r -g > coverage_data/GM12878_0.10_final_peaks.bed


In [34]:
%matplotlib qt

fig = matplotlib.pyplot.figure()
ax = fig.add_subplot(111)

with open("../testdata/coverage_data/GM12878_0.001_final_peaks.bed") as data:
    graph_data_x=[]
    graph_data_y=[]
    for line in data:
        line_info = line.split()
        graph_data_x.append(int(line_info[2])-int(line_info[1]))
        graph_data_y.append(float(line_info[6]))


ax.plot(numpy.array(graph_data_x).cumsum(),numpy.array(graph_data_y).cumsum())

with open("../testdata/coverage_data/GM12878_0.01_final_peaks.bed") as data:
    graph_data_x=[]
    graph_data_y=[]
    for line in data:
        line_info = line.split()
        graph_data_x.append(int(line_info[2])-int(line_info[1]))
        graph_data_y.append(float(line_info[6]))


ax.plot(numpy.array(graph_data_x).cumsum(),numpy.array(graph_data_y).cumsum())

with open("../testdata/coverage_data/GM12878_0.10_final_peaks.bed") as data:
    graph_data_x=[]
    graph_data_y=[]
    for line in data:
        line_info = line.split()
        graph_data_x.append(int(line_info[2])-int(line_info[1]))
        graph_data_y.append(float(line_info[6]))


ax.plot(numpy.array(graph_data_x).cumsum(),numpy.array(graph_data_y).cumsum())

ax.scatter(231706073,47273)

#0.05
#ax.scatter(69524,47273)