notebook that was used to generate figures for paper

In [10]:
import scipy
import scipy.sparse, scipy.stats
import numpy
import os
import re
import multiprocessing
import subprocess
import pickle
import matplotlib.pyplot
import time
import statistics
import sklearn
import statsmodels , statsmodels.api
import itertools
import random
import math

In [7]:
def moving_integration (values, window):
    weights = numpy.repeat(1.0, window)
    sma = numpy.convolve(values, weights, 'same')
    return sma
def moving_average (values, window):
    weights = numpy.repeat(1.0, window)/window
    sma = numpy.convolve(values, weights, 'same')
    return sma

In [2]:
with open("../testdata/T_cell_0.10_final_alldata.pickle","rb") as picklefile:
    CSR_mat,frag_index,frag_prop,frag_amount,valid_chroms,chroms_offsets,smoothed_diagonal, refined_peaks ,quick_peaks, peak_p_vals , peaks_q_vals = pickle.load(picklefile)

In [13]:
#distribution of reads frequency
%matplotlib qt

fig = matplotlib.pyplot.figure()
ax = fig.add_subplot(111)

ax.hist(smoothed_diagonal, bins=50, range=(0,100))

(array([418182., 476201., 610081., 650868., 618416., 548876., 467554.,
        394010., 331785., 280082., 238340., 204065., 175147., 151972.,
        132110., 115744., 101532.,  88664.,  78385.,  68684.,  60755.,
         54175.,  47638.,  43256.,  38857.,  35126.,  31856.,  29137.,
         26488.,  24223.,  22080.,  20208.,  18818.,  17210.,  15883.,
         15102.,  14056.,  13235.,  11992.,  11452.,  10901.,  10139.,
          9574.,   9153.,   8543.,   8223.,   7833.,   7381.,   7093.,
         10021.]),
 array([  0.,   2.,   4.,   6.,   8.,  10.,  12.,  14.,  16.,  18.,  20.,
         22.,  24.,  26.,  28.,  30.,  32.,  34.,  36.,  38.,  40.,  42.,
         44.,  46.,  48.,  50.,  52.,  54.,  56.,  58.,  60.,  62.,  64.,
         66.,  68.,  70.,  72.,  74.,  76.,  78.,  80.,  82.,  84.,  86.,
         88.,  90.,  92.,  94.,  96.,  98., 100.]),
 <a list of 50 Patch objects>)

In [33]:
# distribution of p values after binomial model
%matplotlib qt

fig = matplotlib.pyplot.figure()
ax = fig.add_subplot(111)


ax.hist(peak_p_vals, bins=20, range=(0,1))

(array([845420., 298147., 278410., 277179., 282318., 281376., 305076.,
        310974., 319878., 312041., 397941., 323357., 420140., 401751.,
        330652., 352053., 339556., 384518., 248440., 418182.]),
 array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
        0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  ]),
 <a list of 20 Patch objects>)

In [ ]:
bedtools annotate -counts -i T_cell_0.001_final_peaks.bed -files T_helper_replicated_peaks.bed | sort -k6,6 -r -g > coverage_data/T_cell_0.001_final_peaks.bed
bedtools annotate -counts -i T_cell_0.01_final_peaks.bed -files T_helper_replicated_peaks.bed | sort -k6,6 -r -g > coverage_data/T_cell_0.01_final_peaks.bed
bedtools annotate -counts -i T_cell_0.10_final_peaks.bed -files T_helper_replicated_peaks.bed | sort -k6,6 -r -g > coverage_data/T_cell_0.10_final_peaks.bed


In [48]:
%matplotlib qt

fig = matplotlib.pyplot.figure()
ax = fig.add_subplot(111)

with open("../testdata/coverage_data/T_cell_0.001_final_peaks.bed") as data:
    graph_data_x=[]
    graph_data_y=[]
    for line in data:
        line_info = line.split()
        graph_data_x.append(int(line_info[2])-int(line_info[1]))
        graph_data_y.append(float(line_info[6]))


ax.plot(numpy.array(graph_data_x).cumsum(),numpy.array(graph_data_y).cumsum())

with open("../testdata/coverage_data/T_cell_0.01_final_peaks.bed") as data:
    graph_data_x=[]
    graph_data_y=[]
    for line in data:
        line_info = line.split()
        graph_data_x.append(int(line_info[2])-int(line_info[1]))
        graph_data_y.append(float(line_info[6]))


ax.plot(numpy.array(graph_data_x).cumsum(),numpy.array(graph_data_y).cumsum())

with open("../testdata/coverage_data/T_cell_0.10_final_peaks.bed") as data:
    graph_data_x=[]
    graph_data_y=[]
    for line in data:
        line_info = line.split()
        graph_data_x.append(int(line_info[2])-int(line_info[1]))
        graph_data_y.append(float(line_info[6]))


ax.plot(numpy.array(graph_data_x).cumsum(),numpy.array(graph_data_y).cumsum())

ax.scatter(125462713,32969)

#0.05
#ax.scatter(41530,32969)

In [23]:
bedtools annotate -counts -i GM12878_0.001_final_peaks.bed -files GM12878_replicated_peaks.bed | sort -k6,6 -r -g > coverage_data/GM12878_0.001_final_peaks.bed
bedtools annotate -counts -i GM12878_0.01_final_peaks.bed -files GM12878_replicated_peaks.bed | sort -k6,6 -r -g > coverage_data/GM12878_0.01_final_peaks.bed
bedtools annotate -counts -i GM12878_0.10_final_peaks.bed -files GM12878_replicated_peaks.bed | sort -k6,6 -r -g > coverage_data/GM12878_0.10_final_peaks.bed


In [34]:
%matplotlib qt

fig = matplotlib.pyplot.figure()
ax = fig.add_subplot(111)

with open("../testdata/coverage_data/GM12878_0.001_final_peaks.bed") as data:
    graph_data_x=[]
    graph_data_y=[]
    for line in data:
        line_info = line.split()
        graph_data_x.append(int(line_info[2])-int(line_info[1]))
        graph_data_y.append(float(line_info[6]))


ax.plot(numpy.array(graph_data_x).cumsum(),numpy.array(graph_data_y).cumsum())

with open("../testdata/coverage_data/GM12878_0.01_final_peaks.bed") as data:
    graph_data_x=[]
    graph_data_y=[]
    for line in data:
        line_info = line.split()
        graph_data_x.append(int(line_info[2])-int(line_info[1]))
        graph_data_y.append(float(line_info[6]))


ax.plot(numpy.array(graph_data_x).cumsum(),numpy.array(graph_data_y).cumsum())

with open("../testdata/coverage_data/GM12878_0.10_final_peaks.bed") as data:
    graph_data_x=[]
    graph_data_y=[]
    for line in data:
        line_info = line.split()
        graph_data_x.append(int(line_info[2])-int(line_info[1]))
        graph_data_y.append(float(line_info[6]))


ax.plot(numpy.array(graph_data_x).cumsum(),numpy.array(graph_data_y).cumsum())

ax.scatter(231706073,47273)

#0.05
#ax.scatter(69524,47273)

In [46]:
# fragment size bias
# self-circle and dangling ends pairs only. Plot lowess fit of fragment size to number of reads
#maybe integrate the thing for the maximum and minimum size below as well
res_frag_mat = scipy.sparse.load_npz('../../domain_caller/testdata/sparse_matrix_mumbach.npz')
SC_DE_pairs = res_frag_mat.diagonal(k=0) #self circle and dangling end pairs
sizes=[]
for i in frag_prop:
    sizes.append(i[3])
    
sizes_sub, SC_DE_pairs_sub = zip(*random.sample(list(zip(sizes, SC_DE_pairs)), 50000))
y = statsmodels.api.nonparametric.lowess(SC_DE_pairs_sub, sizes_sub,return_sorted=False,frac=0.2,delta=10.0)
%matplotlib qt
fig, ax = matplotlib.pyplot.subplots()
ax.scatter(sizes_sub,y)
fig.show()

In [44]:
# fragment size bias with our method

lengths = [x[3] for x in frag_prop] 
group_lengths = moving_integration(lengths, 2)  ###changed to 2, so the 2 fragments within
min_allowed_size = math.floor(numpy.percentile(group_lengths, 1))
max_allowed_size = math.floor(numpy.percentile(group_lengths, 99))
# add 1s to quick peaks to exclude them from the noise modelling
noise_filter = quick_peaks.copy()
for i in range(len(group_lengths)):
    if group_lengths[i] > max_allowed_size or group_lengths[i] < min_allowed_size:
        noise_filter[i] = 1

# select only the bits that give you noise. On which to model stuff
noise_lengths = list(itertools.compress(group_lengths, [not i for i in noise_filter]))
noise_diagonal = list(itertools.compress(smoothed_diagonal, [not i for i in noise_filter]))

idx = numpy.random.choice(len(noise_lengths), size=200000, replace=False)
subset_lengths = [noise_lengths[n] for n in idx]
subset_diagonal = [noise_diagonal[n] for n in idx]
# find lowess prediction
predicted_stuff = statsmodels.api.nonparametric.lowess(subset_diagonal, subset_lengths,return_sorted=True, frac=0.4 , delta=3.0 ) 
predicted_lengths = list(zip(*predicted_stuff))[0]
predicted_diagonals = list(zip(*predicted_stuff))[1]

%matplotlib qt
fig, ax = matplotlib.pyplot.subplots()
ax.scatter(predicted_lengths,predicted_diagonals)
fig.show()

In [45]:
# fit on the diagonal without smoothing. using the size of the restriction fragment before and after
from context import hichip_tool

from hichip_tool import sparse_to_peaks

non_smooth_diagonal = sparse_to_peaks.extract_diagonal(CSR_mat,2)[0]

idx = numpy.random.choice(len(group_lengths), size=200000, replace=False)
subset_lengths = [group_lengths[n] for n in idx]
subset_diagonal = [non_smooth_diagonal[n] for n in idx]
# find lowess prediction
predicted_stuff = statsmodels.api.nonparametric.lowess(subset_diagonal, subset_lengths,return_sorted=True, frac=0.4 , delta=3.0 ) 
predicted_lengths = list(zip(*predicted_stuff))[0]
predicted_diagonals = list(zip(*predicted_stuff))[1]

%matplotlib qt
fig, ax = matplotlib.pyplot.subplots()
ax.scatter(predicted_lengths,predicted_diagonals)
fig.show()

In [24]:
from context import hichip_tool

from hichip_tool import sparse_to_peaks

sparse_to_peaks.extract_diagonal(CSR_mat,2)[1]
round(sum(smoothed_diagonal)/3)

82782600.0

In [26]:
sum(res_frag_mat.diagonal(k=0)) + sum(res_frag_mat.diagonal(k=1)) 

61810283

In [33]:
# import matplotlib.backends.backend_pdf
# pdf = matplotlib.backends.backend_pdf.PdfPages("output.pdf")
# for fig in xrange(1, figure().number): ## will open an empty extra figure :(
#     pdf.savefig( fig )
# pdf.close()

82782600.0

In [42]:

fig, ax = matplotlib.pyplot.subplots()

ax.text(0.1, 0.1, 'matplotlib')
ax.axis("off")
ax.table(cellText=None, cellColours=None,
      cellLoc='right', colWidths=None,
      rowLabels=None, rowColours=None, rowLoc='left',
      colLabels=None, colColours=None, colLoc='center',
      loc='bottom', bbox=None)
fig.show()

ValueError: At least one argument from "cellColours" or "cellText" must be provided to create a table.